feature(agent): add support for Universal eBPF
sysdiglabs/charts pull request #1270
Opened 2023-07-27 10:28 UTC by mavimo

## What this PR does / why we need it:

 - Add support for the Universal eBPF driver

## Checklist

- [x] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [x] Chart Version bumped for the respective charts
- [ ] Variables are documented in the README.md (or README.tpl in some charts)
- [x] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [x] All test files are added in the tests folder of their respective chart and have a "_test" suffix

2023-07-27 10:44 UTC, AlbertoBarba requested changes

2023-07-27 10:44 UTC, AlbertoBarba commented on charts/agent/templates/daemonset.yaml
> +          {{- if (include "agent.universalEbpfEnforced" .) }}
I think this env is not needed...if `agent.universalEbpfEnforced` returns true we don't start the `initContainer`

2023-08-04 15:41 UTC, AlbertoBarba approved these changes

2023-10-17 19:05 UTC, aroberts87 approved these changes
LGTM! Just two small nits.

2023-10-17 19:05 UTC, aroberts87 commented on charts/agent/tests/universal_ebpf_test.yaml
> +  - it: Ensure that when the eBPF is disabled we create the sysdig container wihtout SYSDIG_BPF_PROBE and SYSDIG_AGENT_DRIVER environment variables
```suggestion
  - it: Ensure that when the eBPF is disabled we create the sysdig container without SYSDIG_BPF_PROBE and SYSDIG_AGENT_DRIVER environment variables
```

2023-10-17 19:05 UTC, aroberts87 commented on charts/agent/values.yaml
> +  # Define the kind of eBPF driver that can be used in the agent. Can be `legacy_ebpf` or `universal_ebpf`
```suggestion
  # Define the kind of eBPF driver that will be used by the agent. Can be `legacy_ebpf` or `universal_ebpf`
```

2023-10-18 10:46 UTC, merged