fix(node-analyzer): permissions fix for CR sysdig-agent-node-analyzer
sysdiglabs/charts pull request #1272
Opened 2023-07-28 19:02 UTC by a1ex-var1amov

## What this PR does / why we need it:

The PR removes extensive permissions that were provided to ClusterRole sysdig-agent-node-analyzer by the following [commit](https://github.com/sysdiglabs/charts/commit/dedebca2a44e00828d80379c00cafbb50d90db8d). Per tests, the permissions were required for the BenchMark runner; however, kspm-analyzer doesn't require them to function properly. 

The PR is the result of investigating the issue [1253](https://github.com/sysdiglabs/charts/issues/1253).

Please double-check. Thank you!

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [x] Chart Version bumped for the respective charts
- [n/a] Variables are documented in the README.md (or README.tpl in some charts)
- [x] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [n/a] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

2023-08-02 08:16 UTC, ProvoK approved these changes
LGTM for what concerns NIA/RuntimeScanner/HostScanner

2023-08-02 08:29 UTC, dark-vex requested changes

2023-08-02 08:29 UTC, dark-vex commented on charts/node-analyzer/templates/clusterrole-node-analyzer.yaml
> -- apiGroups:
@a1ex-var1amov we still have on-premise customers using the Benchmark Runner, can we add `{{- if (include "nodeAnalyzer.deployBenchmarkRunner" .) }}` for add those additional permission only when `benchmarkRunner.deploy` is set to `true` ?

2023-08-02 09:59 UTC, chen-shmilovich-sysdig approved these changes

2023-08-04 13:37 UTC, dark-vex commented on charts/node-analyzer/templates/clusterrole-node-analyzer.yaml
> -- apiGroups:
Thanks Alex for fixing it

2023-08-04 13:39 UTC, dark-vex approved these changes

2023-08-07 15:17 UTC, merged