feat(KSPM admission controller): SSPROD-35354 - Make Dry Run mode configurable to a user in Chart Values.
sysdiglabs/charts pull request #1560
Opened 2024-01-07 18:45 UTC by dimar-apolicy

## What this PR does / why we need it:
Proposed changes will allow configuring the `dry-run` and the `denyOnError` settings of KSPM admission controller.\
JIRA ticket: [Make Dry Run mode configurable to a user in Chart Values](https://sysdig.atlassian.net/browse/SSPROD-35354)
## Checklist
- [X] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [ ] Chart Version bumped for the respective charts
- [ ] Variables are documented in the README.md (or README.tpl in some charts)
- [ ] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [ ] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

2024-01-08 09:25 UTC, lior-alafi-work requested changes
@dimar-apolicy can you also add the default value to be true?
i.e
value: {{ .Values.webhook.dryRun | default "tea" | quote }}

2024-01-09 09:06 UTC, lior-alafi-work approved these changes

2024-01-11 10:39 UTC, airadier approved these changes

2024-01-15 09:11 UTC, AlbertoBarba commented on charts/admission-controller/templates/webhook/deployment.yaml
> +            - name: DENY_ON_ERROR
Should we configure the [`failurePolicy`](https://github.com/sysdiglabs/charts/blob/master/charts/admission-controller/templates/_helpers.tpl#L416) accordingly?

EG: heres what happens with the webhook right now https://github.com/sysdiglabs/charts/blob/master/charts/admission-controller/templates/_helpers.tpl#L453

2024-01-15 10:31 UTC, dimar-apolicy commented on charts/admission-controller/templates/webhook/deployment.yaml
> +            - name: DENY_ON_ERROR
@AlbertoBarba there is no change in existing logic, just using the value in another container.

2024-01-15 10:42 UTC, AlbertoBarba approved these changes

2024-01-25 12:01 UTC, merged