Grant the agent permissions for listing storageclass resources
sysdiglabs/charts pull request #217
Opened 2021-08-19 11:18 UTC by fremmi

## What this PR does / why we need it:

This PR gives the agent RBAC permissions for handling `storageclass` kubernetes resources

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

2021-09-14 18:37 UTC, bawhetst requested changes
You should update the readme with the changes that are occurring. Also, I have one comment on the appVersion.

2021-09-14 18:37 UTC, bawhetst commented on charts/sysdig/Chart.yaml
> +appVersion: 11.3.0
We shouldn't downgrade the appVersion unless there's a specific reason to.

2021-10-26 13:00 UTC, irozzo-1A approved these changes
LGTM

2021-10-26 13:01 UTC, irozzo-1A commented
@fremmi I think you should rebase

2021-10-26 13:38 UTC, irozzo-1A approved these changes

2021-10-26 13:46 UTC, merged