[runtime-scanner] fix: update runtime-scanner-configmap
sysdiglabs/charts pull request #355
Opened 2022-03-03 21:54 UTC by SysdigDan

## What this PR does / why we need it:

The runtime-scanner-configmap does not set eve_enabled: true correctly. This fixes the resource used in the values.yaml.

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

2022-03-04 09:57 UTC, ProvoK approved these changes

2022-03-04 09:57 UTC, acaprari approved these changes

2022-03-24 16:33 UTC, acaprari requested changes
@SysdigDan can you rebase on `master` to solve conflict on chart version?

We can then merge the PR, thanks!

2022-03-24 21:08 UTC, SysdigDan commented
@acaprari rebase done.

2022-03-24 21:50 UTC, acaprari approved these changes

2022-03-25 17:58 UTC, merged