[SMAGENT-3866] Fix monitorUrl for non-us1 SaaS regions in sysdig-deploy chart
sysdiglabs/charts pull request #488
Opened 2022-07-05 16:23 UTC by divacvl

## What this PR does / why we need it:

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

2022-07-05 17:18 UTC, yashgiri requested changes
Hi @divacvl can you please make the following changes - 

- Include some info in the changelog as Minor changes.
- Change the name of the PR by removing the prefix [SMAGENT-3866] and instead starting it with [sysdig-deploy]

2022-07-05 18:11 UTC, yashgiri approved these changes

2022-07-05 18:52 UTC, lilx1ao approved these changes

2022-07-07 11:21 UTC, achandras approved these changes
lgtm, thanks!

2022-07-07 12:07 UTC, merged