[agent] add certificatesigningrequests
sysdiglabs/charts pull request #622
Opened 2022-09-08 16:34 UTC by fremmi

## What this PR does / why we need it:

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with chart name (e.g. [mychartname])
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md (or README.tpl in some charts)
- [ ]  Check GithubAction checks (like lint) to avoid merge-check stoppers

Check Contribution guidelines in README.md for more insight.

2022-09-08 17:15 UTC, yashgiri requested changes
For file charts/sysdig-deploy/Chart.yaml

agent chart version needs to be updated.

Also sysdig-deploy changelog needs to be updated

2022-09-12 15:23 UTC, yashgiri requested changes

2022-09-12 15:23 UTC, yashgiri commented on charts/agent/Chart.yaml
For this file version of the agent over here : https://github.com/sysdiglabs/charts/blob/c1b2c8740db8f2c6b180cfdb0e12da1f4aa134af/charts/sysdig-deploy/Chart.yaml#L23
will need to be changed.
Edit: For some reason I cannot add the same as a suggestion.

2022-09-13 20:19 UTC, irozzo-1A approved these changes
LGTM

2022-09-20 13:57 UTC, yashgiri approved these changes

2022-09-20 13:58 UTC, irozzo-1A approved these changes
LGTM

2022-09-22 10:17 UTC, merged