[sysdig-deploy][agent] correcting us3 endpoints
sysdiglabs/charts pull request #661
Opened 2022-10-17 18:02 UTC by kadkins-sysdig

## What this PR does / why we need it:

The us3 endpoints are incorrect.

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [x] Title of the PR starts with chart name (e.g. [mychartname])
- [x] Chart Version bumped for the respective charts
- [x] Changelog updated for the charts with version updates.
- [x] Variables are documented in the README.md (or README.tpl in some charts)
- [ ] Check GithubAction checks (like lint) to avoid merge-check stoppers

Check Contribution guidelines in README.md for more insight.

2022-10-17 18:53 UTC, yashgiri commented
Need to include agent and sysdig-deploy changelogs.

2022-10-17 18:56 UTC, yashgiri requested changes
Sorry for the redundant message: Please include the changelogs for agent and sysdig-deploy charts.

2022-10-17 19:48 UTC, yashgiri approved these changes

2022-12-16 21:27 UTC, aroberts87 commented
This is now handled by https://github.com/sysdiglabs/charts/pull/823. Closing this PR.

2022-12-16 21:27 UTC, closed without merging