[sysdig-stackdriver-bridge] feat: Add chart for Stackdriver Bridge
sysdiglabs/charts pull request #72
Opened 2021-01-13 21:24 UTC by echoboomer

## What this PR does / why we need it:
Adds a separate Helm chart per owner's request for Stackdriver Bridge.

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

2021-01-13 21:25 UTC, echoboomer commented
@nestorsalceda As requested, I've opened this feature as a new chart rather than an enhancement to the existing Sysdig chart. Thanks for your time!

2021-01-19 09:28 UTC, nestorsalceda requested changes
Just a few issues, once these are solved we will merge.

Thank you very much!

2021-01-19 09:28 UTC, nestorsalceda commented on charts/sysdig-stackdriver-bridge/Chart.yaml
> +appVersion: 0.0.4
Upgrade to 0.0.5, please.

It was released a couple of hours ago

2021-01-19 09:28 UTC, nestorsalceda commented on charts/sysdig-stackdriver-bridge/README.md
> +| `image.tag`             | Image tag.                                                                                                                                             | `latest`
We use fixed tags for this, it can be empty and it will honor the appVersion from Chart.yaml file

2021-01-19 09:28 UTC, nestorsalceda commented on charts/sysdig-stackdriver-bridge/templates/deployment.yaml
> +          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
Replace with this default: 

image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"

2021-01-19 13:49 UTC, echoboomer commented
@nestorsalceda All of the above issues have been addressed, but I'm going to leave `image.tag=v0.0.5` for now since there are some inconsistencies in the image tagging for the `stackdriver-webhook-bridge` [repository](https://hub.docker.com/r/sysdiglabs/stackdriver-webhook-bridge/tags?page=1&ordering=last_updated).

Before the most recent releases, tags were numeric - i.e. `0.0.3` - now they include `v`, so the latest is `v0.0.5`. We could add in the `v` natively in the chart, but this seems like an unoptimized way to do this. For now, this mimics the behavior you have in the `sysdig` chart - set `image.tag` to the same version as what is in `Chart.yaml`, but it can be overridden at will.

2021-01-21 14:15 UTC, merged

2021-01-21 14:20 UTC, nestorsalceda commented
Thank you very much @echoboomer !