docs(admission-controller): troubleshoot sourceIp support
sysdiglabs/charts pull request #885
Opened 2023-01-11 17:08 UTC by wideawakening

## What this PR does / why we need it:

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [ ] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [ ] Chart Version bumped for the respective charts
- [ ] Variables are documented in the README.md (or README.tpl in some charts)
- [ ] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [ ] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

2023-01-16 10:22 UTC, giuse-sysdig requested changes
The solution proposed in the doc change seems a loop because the doc requests to install the Admission Controller "To enable this feature in Sysdig Secure SaaS, install the Sysdig Admission Controller and set the features.k8sAuditDetections to true". SO I would avoid adding the request to use Agent + K8S Audit or change the doc to do the same without leveraging on AC.

2023-01-23 07:16 UTC, wideawakening commented
> The solution proposed in the doc change seems a loop because the doc requests to install the Admission Controller "To enable this feature in Sysdig Secure SaaS, install the Sysdig Admission Controller and set the features.k8sAuditDetections to true". SO I would avoid adding the request to use Agent + K8S Audit or change the doc to do the same without leveraging on AC.

corrected the link to point to the workaround and avoid loop

2023-01-27 08:34 UTC, hayk99 approved these changes

2023-02-17 09:03 UTC, giuse-sysdig approved these changes
lgtm

2023-02-17 09:13 UTC, merged