fix(sysdig-deploy,node-analyzer,kspm-collector): Fix security context permission for KSPM components
sysdiglabs/charts pull request #907
Opened 2023-01-30 13:40 UTC by dark-vex

## What this PR does / why we need it:

When deploying sysdig-deploy chart with the flag `--set global.kspm.deploy=true` (which is the default now), `node-analyzer` (due to kspm-analyzer container) and `kspm-collector` pods are not getting deployed on OpenShift due to OCP SCC permission.

For `node-analyzer` kspm-analyzer container we are exposing container and host port 12000 for the readiness/liveness check which is not required because kubernetes/ocp is capable to run this health-checks without exposing the container port. I have removed the `containerPort` and adjusted the readiness/liveness check for kspm-analyzer container.

For `kspm-collector` same thing, in this case we don't have the manifest that request the OCP SCC permission, so in addition to the containerPort change, I have also added `securitycontextconstraint.yaml` manifest

### Prior the change
```
 ➜ oc get ds,deploy -n sysdig-agent
NAME                                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/sysdig-agent                 6         6         4       6            4           <none>          2m14s
daemonset.apps/sysdig-agent-node-analyzer   0         0         0       0            0           <none>          2m14s

NAME                                         READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sysdig-agent-kspmcollector   0/1     0            0           2m14s
```

### After the change
```
 ➜ oc get po -n sysdig-agent
NAME                                          READY   STATUS    RESTARTS   AGE
sysdig-agent-6kzwd                            1/1     Running   0          11m
sysdig-agent-8nvvm                            1/1     Running   0          11m
sysdig-agent-dq5g7                            1/1     Running   0          11m
sysdig-agent-kspmcollector-857fcdf96b-z4g8q   1/1     Running   0          3m13s
sysdig-agent-mhc9t                            1/1     Running   0          11m
sysdig-agent-node-analyzer-58mfg              3/3     Running   0          3m14s
sysdig-agent-node-analyzer-6rkql              3/3     Running   0          3m14s
sysdig-agent-node-analyzer-bdtdd              3/3     Running   0          3m14s
sysdig-agent-node-analyzer-bh945              3/3     Running   0          3m14s
sysdig-agent-node-analyzer-pcncf              3/3     Running   0          3m14s
sysdig-agent-node-analyzer-vbhv7              3/3     Running   0          3m14s
sysdig-agent-qfcgz                            1/1     Running   0          11m
sysdig-agent-s78tq                            1/1     Running   0          11m
```

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [X] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [X] Chart Version bumped for the respective charts
- [X] Variables are documented in the README.md (or README.tpl in some charts)
- [ ] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [ ] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

2023-01-30 14:41 UTC, ido-gold-apolicy commented on charts/kspm-collector/templates/deployment.yaml
> +          httpGet:
Are we overriding the probe configuration behavior on purpose?

2023-01-30 14:52 UTC, dark-vex commented on charts/kspm-collector/templates/deployment.yaml
> +          httpGet:
Yes,  this is on purpose, current implementation have `port` value for liveness and readiness set to `http`. Since we are removing `containerPort` definition from kspm-analyzer container that value is no longer valid.

In order to avoid specifying 3 times the port 12000 (which could be error prone from end-user) on the values.yaml:
https://github.com/sysdiglabs/charts/blob/master/charts/node-analyzer/values.yaml#L370
https://github.com/sysdiglabs/charts/blob/master/charts/node-analyzer/values.yaml#L377
https://github.com/sysdiglabs/charts/blob/master/charts/node-analyzer/values.yaml#L385

This is the reason of this change

2023-01-30 16:54 UTC, aroberts87 requested changes
Hey @dark-vex ! Manually adjusting the dependency versions in the sysdig-deploy chart are no longer required. There is a GitHub action that runs when PRs are merged and detects if a version bump needs to be made to the sysdig-deploy chart needs to happen and takes care of it automatically. Please remove the manual bump. Thanks!

2023-01-30 18:06 UTC, dark-vex commented
Hey @aroberts87 thanks! Yeah, I have see the PR of the new GH action but I didn't noticed that has been merged :) I will remove `sysdig-deploy` version bump, thanks for the heads-up!

2023-01-31 07:56 UTC, ido-gold-apolicy commented on charts/kspm-collector/templates/deployment.yaml
> +          httpGet:
Got it, thanks

2023-02-06 20:30 UTC, aroberts87 approved these changes

2023-02-07 08:42 UTC, merged