chore(sysdig-deploy,admissionc-controller): bump admission to 3.9.16
sysdiglabs/charts pull request #908
Opened 2023-01-30 16:45 UTC by wideawakening

## What this PR does / why we need it:

## Checklist

[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]

- [X] Title of the PR starts with type and scope, (e.g. feat(agent,node-analyzer,sysdig-deploy):)
- [X] Chart Version bumped for the respective charts
- [ ] Variables are documented in the README.md (or README.tpl in some charts)
- [ ] Check GithubAction checks (like lint) to avoid merge-check stoppers
- [ ] All test files are added in the tests folder of their respective chart and have a "_test" suffix

Check Contribution guidelines in README.md for more insight.

2023-01-30 16:48 UTC, aroberts87 requested changes
Hey @wideawakening! You do not need to manually version bump the admission controller chart in the sysdig-deploy dependencies anymore. Once the changes to the admission controller chart get merged there is a GitHub action that is triggered to bump the dependencies in sysdig-deploy. Please remove the manual bump from this PR. Thanks!

2023-01-30 16:48 UTC, wideawakening commented
> Hey @wideawakening! You do not need to manually version bump the admission controller chart in the sysdig-deploy dependencies anymore. Once the changes to the admission controller chart get merged there is a GitHub action that is triggered to bump the dependencies in sysdig-deploy. Please remove the manual bump from this PR. Thanks!

good to know, thanks! :)

2023-01-31 10:37 UTC, hayk99 approved these changes

2023-01-31 10:39 UTC, d-enz approved these changes

2023-01-31 18:42 UTC, aroberts87 approved these changes
as discussed in slack, the changelog messages are also automatically generated now and link back to the PR. that said, the way you've done this message shouldn't break the workflow so i'll approve this, but wanted to let you know for next time. 🙂

2023-01-31 18:42 UTC, merged